services:
  postgres:
    container_name: project-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    networks:
      - next
    volumes:
     - db:/var/lib/postgresql/data

  dev:
    container_name: project-dev
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
      args:
        PROJECT: ${PROJECT}
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - next
    depends_on:
      - postgres

volumes:
  db:

networks:
  next:
    name: next