services:
  dev:
    container_name: project-dev
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
      args:
        PROJECT: ${PROJECT}
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1

  postgres:
    container_name: project-postgres
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
     - db:/var/lib/postgresql/data

volumes:
  db: