packages:
  - "apps/**"
  - "packages/**"

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  lucide-react: ^0.468.0
  tailwindcss: ^3.4.16
  typescript: ^5.7.2
  "@types/node": ^22.10.1
  "@types/react": "^19.0.1"
  "@types/react-dom": "^19.0.1"
  "prettier": "^3.4.2"
  "prettier-plugin-tailwindcss": "^0.6.9"
  "tsx": "^4.19.2"
  "react-hook-form": "^7.54.0"
  "@hookform/resolvers": "^3.9.1"
  "@prisma/client": "^6.0.1"
  "@cgambrell/utils": "^2.0.0"
  "@auth/prisma-adapter": "^2.7.4"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "next": "^15.0.3"
  "next-auth": "5.0.0-beta.25"
  "tailwind-merge": "^2.5.5"
  "tailwindcss-animate": "^1.0.7"
  "zod": "^3.23.8"
  "prisma": "^6.0.1"
  "autoprefixer": "^10.4.20"
  "postcss": "^8.4.49"
  "@vercel/style-guide": "^6.0.0"
  "eslint-config-turbo": "^2.3.3"