name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
            docker compose build --profile prod
      - name: Push Docker image
        run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-app:${{ github.sha }}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-app:latest