name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Echo Docker Hub Username
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Echo GitHub SHA
        run: echo $GITHUB_SHA

      - name: Build Docker image
        id: build_image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate:$GITHUB_SHA --profile prod"
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate:$GITHUB_SHA

      - name: Logout from Docker Hub
        run: docker logout

      - name: End
        run: echo "Docker image pushed to Docker Hub successfully"
