name: Release Drafter

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
