name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm turbo run build

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate-app:${{ github.ref_name }} -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate-app:latest -f docker/prod/app/dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate-app:latest
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate-docs:${{ github.ref_name }} -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate-docs:latest -f docker/prod/docs/dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate-docs:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-boilerplate-docs:latest
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
