name: Release Drafter

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04

    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
